### ISSUE TITLE
Broken link for 4th part of Elm vs PureScript article

### ISSUE THREAD

**Issue by PavloKovalov** [parsonsmatt/parsonsmatt.github.io#2]
On this page http://www.parsonsmatt.org/2015/10/10/elm_architecture_in_purescript_iii.html
There is a link to 4th chapter that leads to 404. Url is 
`http://www.parsonsmatt.org/2015/10/11/elm_architecture_in_purescript_iv:_effects.html`
instead of 
`http://www.parsonsmatt.org/2015/10/11/elm_architecture_in_purescript_iv-_effects.html`

**Comment by parsonsmatt** [comment]
Thanks for letting me know! :smile:
