### ISSUE TITLE
[Question] Basic Type Level Programming in Haskell

### ISSUE THREAD

**Issue by coodoo** [parsonsmatt/parsonsmatt.github.io#24]
Trying to follow along the example and hit a wall on this one:

```haskell
instance (Show (HList as), Show a) 
    => Show (HList (a ': as)) where
    show (a ::: rest) = 
        show a ++ " ::: " ++ show rest
```
When I try to run it in `ghci`, I got following error messages:

```
> "hello" ::: HNil

<interactive>:53:1: error:
    • No instance for (Show (HList '[])) arising from a use of ‘print’
    • In a stmt of an interactive GHCi command: print it
```

Although the code in `hs` file does seem to compile fine, I'm guessing this might be caused by `ghci` not adding in correct language extensions? Would appreciate any help, thanks.

**Comment by parsonsmatt** [comment]
You need to also define an instance `Show (HList '[])`. The two instances are both necessary to print a list out. The `Show (HList (a ': as))` is used for the elements of the list, and then the `Show (HList '[])` is used to print the end of the list.

**Comment by coodoo** [comment]
Thanks!
