### ISSUE TITLE
Topic Request: How to Organize Information

### ISSUE THREAD

**Issue by StevenXL** [parsonsmatt/parsonsmatt.github.io#50]
Hello @parsonsmatt,

Thank you first and foremost for your blog. It is a fantastic resource. 

This might fall outside of the topics that you usually write about, but I would love to understand your methodology for learning new topics. Let's imagine, for example, that you knew nothing about type-level programming. How would you go about learning that material. The goal, of course, is going to be to generalize the "how to learn type-level programming" into "how to learn". (This topic is partially inspired by your [Twitter post](https://twitter.com/mattoflambda/status/1303533481654284288?s=20) on organizing information, but I 100% understand if this would dilute the strong Haskell emphasize of your blog).

**Comment by parsonsmatt** [comment]
That's a great question.

Unfortunately, my 'real' answer is "Have ADD and get hyperfocused on some subject, and voraciously consume anything you can find on the subject." I don't have a great track record for learning things I'm not obsessed with :sweat_smile: 

Generally, I think most of programming is [tacit knowledge](https://commoncog.com/blog/tacit-knowledge-is-a-real-thing/) that doesn't get transmitted particularly well through rote reading. Practice, writing, talking, observing, etc are much better means of transmitting that information. So my "stream of thought" blog posts are probably a good example of how I work through things, which may teach more than an explicit description of my thought process.

**Comment by StevenXL** [comment]
Understood! Thank you very much!
