### ISSUE TITLE
GHC is pretty good at compiling modules in parallel

### ISSUE THREAD

**Issue by geraldus** [parsonsmatt/parsonsmatt.github.io#61]
Hi!  Thank you for your "Keeping Compilation Fast" article.

I wonder about the statement in the blog post — "GHC is pretty good at compiling modules in parallel".  I can't figure out how to make GHC compile modules of a same package in parallel.  I did some tests and it looks like that GHC, cabal and stack all do not support this.  Are you talking about compilation with GHC directly in different processes?

**Comment by parsonsmatt** [comment]
With `--ghc-options "-j4 +RTS -N -RTS"` you should get parallel compilation of modules in a package.

**Comment by geraldus** [comment]
OMG, this is indeed works.  Hundred of thousands thanks! You're my hero :)
