### ISSUE TITLE
Extensible Records

### ISSUE THREAD

**Issue by EdmundsEcho** [parsonsmatt/parsonsmatt.github.io#9]
Great post.  I was able to work through the code up to the point I hit the Extensible Record section.  I keep getting a "parse error on input '@'".  At this point, my brain is a bit fried (it's near the end of a great post).  So, I might be making a silly mistake.  This said, I've tried a few workarounds and can't seem to figure it out.  The code is as you have it in the post.  Thank you in advance.  - E

<img width="560" alt="screen shot 2018-05-06 at 11 49 10 am" src="https://user-images.githubusercontent.com/11245417/39675057-94c270f2-5123-11e8-9206-b0bac9d7ef36.png">

**Comment by parsonsmatt** [comment]
That syyntax is the `TypeApplications` extension. Try doing `:set -XTypeApplications` in GHCi to turn it on :)

**Comment by EdmundsEcho** [comment]
It worked.  Specifically, I had the extensions in the module, but unlike what I normally have had to do for other extensions, I also needed to `:set -XTypeApplications` and `:set -XDataKinds` in GHCi.  Perfect.  ... and yes, that cat on your shoulder does make you look cool!  That and how well you write about how to bake a cake in Haskell.  Great stuff.  Thank you.  - E

**Comment by parsonsmatt** [comment]
Thanks for the kind words :smile:
